version: "3.9"
services:
  chatboat:
    container_name: chatboat
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "${HOST_PORT}:8080"