version: "3.9"
services:
  chatboat:
    container_name: chatboat
    image: dockingaman/amakv_chatboat:v0.0.1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 8085:8080